import type { Metadata } from "next";
import { Inria_Sans, Scheherazade_New } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import { getCategories, siteDetails} from "@/sanity/libs/api";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inriaSans = Inria_Sans({
  variable: "--font-inria-sans",
  weight: "300",
  subsets: ["latin"], 
});

const scheherazadeNew = Scheherazade_New({
  variable: "--font-scheherazade-new",
  weight: "400",
  subsets: ["arabic", "latin"], 
});

// export const metadata: Metadata = {
//   title: "Breathe Spa",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const site = await getSiteData();
  const site = await siteDetails();
  const service = await getCategories()

  return (
    <html lang="en">
      <body className={`${scheherazadeNew.variable} ${inriaSans.variable}`}>
        <Header site={site} />
          {children}
        <Footer site={site} service={service} />
      </body>
    </html>
  );
}


export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Breathe Spa",
    description: "Welcome to Breathe Spa, your destination for wellness, relaxation, and pampering.",
    icons: {
      icon: '/BreatheLogo25Black.png',
    },
  };
}


